     141Grass-Hayland                                   Hay                    22     141  141
     141Grass-Hayland                                   Hay_ir                 23     141  141
     142Legume-Hayland                                  Alfalfa                24     142  142
     142Legume-Hayland                                  Alfalfa_ir             25     142  142
     211Grass-Pastureland                               Other_grass            26     211  211
     211Grass-Pastureland                               Other_grass_ir         27     211  211
     114Barley-Close Grown                              Barley                 28     114  114
     114Barley-Close Grown                              Barley_ir              29     114  114
       0                                                BeansEdible            30     501  501
       0                                                BeansEdible_ir         31     501  501
      11Corn-Row Crops                                  CornGrain              32      11   11
      11Corn-Row Crops                                  CornGrain_ir           33      11   11
       0                                                CornSilage             34      11   11
       0                                                CornSilage_ir          35      11   11
      14Cotton-Row Crops                                Cotton                 36      14   14
      14Cotton-Row Crops                                Cotton_ir              37      14   14
     112Oats-Close Grown                                Oats                   38     112  112
     112Oats-Close Grown                                Oats_ir                39     112  112
      15Peanuts-Row Crops                               Peanuts                40      15   15
      15Peanuts-Row Crops                               Peanuts_ir             41      15   15
      18Potatoes-Row Crops                              Potatoes               42      18   18
      18Potatoes-Row Crops                              Potatoes_ir            43      18   18
     113Rice-Close Grown                                Rice                   44     113  113
     113Rice-Close Grown                                Rice_ir                45     113  113
       0                                                Rye                    46     501  501
       0                                                Rye_ir                 47     501  501
      12Sorghum-Row Crops                               SorghumGrain           48      12   12
      12Sorghum-Row Crops                               SorghumGrain_ir        49      12   12
       0                                                SorghumSilage          50      12   12
       0                                                SorghumSilage_ir       51      12   12
      13Soybeans-Row Crops                              Soybeans               52      13   13
      13Soybeans-Row Crops                              Soybeans_ir            53      13   13
       0                                                Wheat_Spring           54     111  111
       0                                                Wheat_Spring_ir        55     111  111
       0                                                Wheat_Winter           56     111  111
       0                                                Wheat_Winter_ir        57     111  111
       0                                                Other_Crop             58     500  500
       0                                                Other_Crop_ir          59     500  500
