unzip  Alfalfa.zip
unzip  Barley.zip
unzip  Canola.zip
unzip  Corng.zip
unzip  Corns.zip
unzip  Cotton.zip
unzip  EdibleBeans.zip
unzip  Hay.zip
unzip  Oats.zip
unzip  OthCrop.zip
unzip  OthGrass.zip
unzip  Peanuts.zip
unzip  Peas.zip
unzip  Potatoes.zip
unzip  Rice.zip
unzip  Rye.zip
unzip  SorghumG.zip
unzip  SorghumS.zip
unzip  Soybean.zip
unzip  SWheat.zip
unzip  temp.csh
unzip  WWheat.zip
